export * from './Movies/Movies'
export * from './Movie/Movie'
export * from './Header/Header'
export * from './MovieDetails/MovieDetails'
export * from './Animated/Animated'
export * from './User/User'
export * from './Genres/Genres'
export * from './Genre/Genre'
